// Auto-generated by inject_version_define.py - DO NOT EDIT
// Source: library.json

#ifndef OTA_UPDATE_VERSION_AUTOGEN_H
#define OTA_UPDATE_VERSION_AUTOGEN_H

#define WEB_MODULE_VERSION_STR "0.1.0"
#define WEB_MODULE_VERSION "0.1.0"

#endif // OTA_UPDATE_VERSION_AUTOGEN_H
